volumes:
  volume_name:
    name: volume_name

services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres-db
    ports:
      - "5434:5432"
    volumes:
      - volume_name:/var/lib/postgresql/data